language: java
jdk:
  - oraclejdk8
notifications:
  email: false
# Disable the default build process
install: true
# Use custom build process instead
script:
  - mvn clean install -Pcobertura -Pcobertura-report -Pcoveralls -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID
addons:
  apt:
    packages:
      - oracle-java8-installer
